name: cloud_firestore_odm_generator
description: A code generator for cloud_firestore_odm.
homepage: https://firebase.flutter.dev/docs/firestore/odm
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.0.0-dev.85

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  analyzer: ">=6.7.0"
  build: ^2.4.1
  build_config: ^1.1.1
  cloud_firestore_odm: ^1.0.0-dev.85
  collection: ^1.19.0
  freezed_annotation: ">=2.4.1"
  # Can be removed once this is fixed https://github.com/dart-lang/graphs/issues/86
  graphs: ^2.3.1
  json_annotation: ^4.9.0
  meta: ^1.14.0
  recase: ^4.1.0
  source_gen: ^1.5.0
  source_helper: ^1.3.4

dependency_overrides:
  cloud_firestore_odm:
    path: ../cloud_firestore_odm

dev_dependencies:
  build_runner: ^2.4.11
  expect_error: ^1.0.7
  json_serializable: ">=6.8.0"
  matcher: ^0.12.16
  test: ^1.25.7
